// combined threejs code

// @koala-append "threejs/three-r73.min.js"
// @koala-append "threejs/Projector.js"
// @koala-append "threejs/CanvasRenderer.js"
// @koala-append "threejs/OrbitControls.js"
// @koala-append "threejs/CombinedCamera.js"
// @koala-append "threejs/OBJMTLLoader.js"
// @koala-append "threejs/MTLLoader.js"
// @koala-append "threejs/OBJExporter.js"
// @koala-append "threejs/Gizmo.js"
// @koala-append "threejs/ctm/lzma.js"
// @koala-append "threejs/ctm/ctm.js"
// @koala-append "threejs/ctm/CTMLoader.js"
// @koala-append "threejs/RenderPass.js"
// @koala-append "threejs/ShaderPass.js"
// @koala-append "threejs/MaskPass.js"
// @koala-append "threejs/CopyShader.js"
// @koala-append "threejs/SSAOShader.js"
// @koala-append "threejs/FXAAShader.js"
// @koala-append "threejs/XRayShader.js"
// @koala-append "threejs/EffectComposer.js"
// @koala-append "threejs/DepthPassPlugin.js"
// @koala-append "threejs/stats.min.js"